// Performance measurements (P6-08). Not a pass/fail gate beyond loose ceilings —
// the numbers are written to docs/performance.md for the results chapter.
//
// Run: flutter test test/performance/performance_test.dart

import 'dart:io';

import 'package:drift/native.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:myhealthcare/app/app.dart';
import 'package:myhealthcare/core/di.dart';
import 'package:myhealthcare/data/db/app_database.dart';
import 'package:myhealthcare/data/repositories/record_repository_impl.dart';
import 'package:myhealthcare/data/seed/seeder.dart';
import 'package:myhealthcare/domain/entities/entities.dart';
import 'package:myhealthcare/domain/enums.dart';
import 'package:myhealthcare/services/ai/ai_models.dart';
import 'package:myhealthcare/services/ai/mock_ai_service.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../support/test_database.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  final results = <String, String>{};

  test('seed + timeline query + DB size', () async {
    final dir = await Directory.systemTemp.createTemp('mhc_perf');
    addTearDown(() => dir.delete(recursive: true));
    final file = File('${dir.path}/perf.sqlite');
    final db = AppDatabase(NativeDatabase(file));
    addTearDown(db.close);

    final seedSw = Stopwatch()..start();
    await Seeder(db).run();
    seedSw.stop();
    results['Seed database (12 staff, ~60 patients, full history)'] =
        '${seedSw.elapsedMilliseconds} ms';

    // Pick the patient with the most records for a worst-case timeline load.
    final records = RecordRepositoryImpl(db);
    final counts = await db
        .customSelect(
          'SELECT patient_id, COUNT(*) c FROM medical_records '
          'GROUP BY patient_id ORDER BY c DESC LIMIT 1',
        )
        .getSingle();
    final busiest = counts.read<String>('patient_id');

    final querySw = Stopwatch()..start();
    final timeline = (await records.timeline(busiest, limit: 500)).valueOrNull!;
    querySw.stop();
    results['Timeline query (busiest patient, ${timeline.length} records)'] =
        '${querySw.elapsedMicroseconds / 1000} ms';

    await db.customStatement('PRAGMA wal_checkpoint(FULL)');
    final bytes = await file.length();
    results['Database file size after seed'] =
        '${(bytes / 1024).toStringAsFixed(0)} KiB';

    expect(seedSw.elapsedMilliseconds, lessThan(60000));
    expect(querySw.elapsedMilliseconds, lessThan(500));
  });

  test('mock AI latency (deterministic, offline path)', () async {
    final db = newTestDatabase();
    addTearDown(db.close);

    final svc = MockAiService(
      patient: Patient(
        user: User(
          id: 'p1',
          role: UserRole.patient,
          fullName: 'P',
          email: 'p@e.com',
          isActive: true,
          createdAt: DateTime(2020),
        ),
      ),
      records: const [],
      vitals: const [],
      medications: const [],
    );
    const ctx = PatientContext(
      patientId: 'p1',
      contextText: 'x',
      hash: 'h',
      approxTokens: 1,
    );

    final sw = Stopwatch()..start();
    for (var i = 0; i < 20; i++) {
      await svc.summarizeRecords(ctx);
    }
    sw.stop();
    results['Mock AI summary (mean of 20)'] =
        '${(sw.elapsedMicroseconds / 20 / 1000).toStringAsFixed(1)} ms';
  });

  testWidgets('cold start to first rendered frame', (tester) async {
    final db = newTestDatabase();
    await Seeder(db).run();
    SharedPreferences.setMockInitialValues({});
    final prefs = await SharedPreferences.getInstance();

    final sw = Stopwatch()..start();
    await tester.pumpWidget(
      ProviderScope(
        overrides: [
          sharedPreferencesProvider.overrideWithValue(prefs),
          appDatabaseProvider.overrideWith((ref) {
            ref.onDispose(db.close);
            return db;
          }),
        ],
        child: const MyHealthCareApp(),
      ),
    );
    await tester.pump();
    sw.stop();
    results['App cold start to first frame (test env)'] =
        '${sw.elapsedMilliseconds} ms';

    // let the splash settle so the DB isn't torn down mid-open
    for (var i = 0; i < 8; i++) {
      await tester.pump(const Duration(milliseconds: 80));
    }
  });

  tearDownAll(() async {
    final buf = StringBuffer()
      ..writeln('# Performance measurements (P6-08)')
      ..writeln()
      ..writeln(
        'Generated by `test/performance/performance_test.dart` on '
        '${DateTime.now().toIso8601String().split('T').first}. '
        'Measured in the Flutter test VM (debug, unoptimised) on the dev '
        'machine — treat as relative, not release figures.',
      )
      ..writeln()
      ..writeln('| Metric | Value |')
      ..writeln('| --- | --- |');
    for (final e in results.entries) {
      buf.writeln('| ${e.key} | ${e.value} |');
    }
    buf
      ..writeln()
      ..writeln(
        '_Ceilings asserted in the test: seed < 60 s, timeline query < 500 ms._',
      );
    await File('docs/performance.md').writeAsString(buf.toString());
  });
}
